/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package index.query.struts.action;


import index.query.DAO.AticleDAO;
import index.query.regex.Regex;
import index.query.regex.Regexone;
import index.query.replace.Queryjyreplace;
import index.query.replace.Queryreplace;
import index.query.struts.form.QueryForm;
import index.qurey.DTO.ArticlecontentDTO;

import java.io.BufferedReader;
import java.io.StringReader;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.htmlparser.Node;
import org.htmlparser.NodeFilter;
import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasChildFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.http.ConnectionManager;
import org.htmlparser.lexer.Page;
import org.htmlparser.util.NodeIterator;
import org.htmlparser.util.NodeList;



/** 
 * MyEclipse Struts
 * Creation date: 04-13-2008
 * 
 * XDoclet definition:
 * @struts.action path="/query" name="queryForm" input="/query.jsp" scope="request" validate="true"
 * @struts.action-forward name="fai" path="fail.jsp"
 * @struts.action-forward name="suc" path="suc.jsp"
 */
public class QueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QueryForm queryForm = (QueryForm) form;// TODO Auto-generated method stub
		
		
	
		
		
		/*
		 * 获取页面的值
		 */
		String name = queryForm.getName();
		
		String name1 = queryForm.getName1();
		
		String name2 = queryForm.getName2();
		
		String name3 = queryForm.getName3();
		
		String name4 = queryForm.getName4();
		
		String name5 = queryForm.getName5();
		
		String name6 = queryForm.getName6();
		
		
		
	    
		/*
		 * 定义字节数组
		 */
		
		byte b[] = null;
		byte b1[] = null;
		byte b2[] = null;
	    byte b3[] = null;
		byte b4[] = null;
		byte b5[] = null;
		byte b6[] = null;
		
		
		
		try {
			/*
			 * 对字符串重新编码
			 */
			b = name.getBytes("ISO-8859-1");
			b1 = name1.getBytes("ISO-8859-1");
			b2 = name2.getBytes("ISO-8859-1");
			b3 = name3.getBytes("ISO-8859-1");
			b4 = name4.getBytes("ISO-8859-1");
			b5 = name5.getBytes("ISO-8859-1");
			b6 = name6.getBytes("ISO-8859-1");
		} catch (UnsupportedEncodingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		name = new String(b);
		name1 = new String(b1);
		name2 = new String(b2);
		name3 = new String(b3);
		name4 = new String(b4);
		name5 = new String(b5);
		name6 = new String(b6);
		
		if(name.equals("")||name == null)
		{
			name = "";
		}
		if(name1.equals("")||name1 == null)
		{
			name1 = "";
		}
		if(name2.equals("")||name2 == null)
		{
			name2 = "";
		}
		if(name3.equals("")||name3 == null)
		{
			name3 = "";
		}
		if(name4.equals("")||name4 == null)
		{
			name4 = "";
		}
		if(name5.equals("")||name5 == null)
		{
			name5 = "";
		}
		if(name6.equals("")||name6 == null)
		{
			name6 = "";
		}
		
		/*
		 * 从页面提交来的信息存入Session
		 */
		
		
	    request.getSession().setAttribute("name",name);
		request.getSession().setAttribute("name1",name1);
		request.getSession().setAttribute("name2",name2);
		request.getSession().setAttribute("name3",name3);
		request.getSession().setAttribute("name4",name4);
		request.getSession().setAttribute("name5",name5);
		request.getSession().setAttribute("name6",name6);
		
		
		 ConnectionManager manager; //与网页连接
		 String but = null; //获取初次过滤的页面内容
		 String line;  //接收每一行代码
		 Queryreplace replace =  new Queryreplace();//创建一个Replace对象来调用replace方法
		 Queryjyreplace place = new Queryjyreplace(); //创建一个Queryjyreplace对象来调用replace方法进行替换
		 String reline;//用来接受被修改的一行字符串
	 	 int i;//循环的次数
		 String equit = "equit";//判断有多少页		 
	   	 BufferedReader reader = null ; //为了得到readLine()方法进行对页面代码读取对字符串进行封装
	     String regex = null;//经过过滤之后的字符串
	   	//获取处理后的字符串
	   	//StringBuffer clear = new StringBuffer();
	     HttpSession session = request.getSession();//创建一个Session对象存数据
	     //HttpSession session1 = request.getSession();//创建一个Session对象存页数据
	   	 int n;//网页的页数
	   	 AticleDAO aticledao = new AticleDAO(); //创建AticleDAO对象来操作存储网页内容
	   	 ArticlecontentDTO articledto = new ArticlecontentDTO(); //存储网页内容
	   	 List list = new ArrayList();//接受dao返回的数据
	   	 
	   	String regexon = null; //一个对网页http://ic.sia.cn/qikan/coldpaperdo.asp信息提取的使用正则表达式
	   	 
	   	 /*
		  * 一个网站一次查询最多能够查询一千条信息出来
		  */
		
	   	 for(i = 1;i<100;i++)
		  { n = i;
		 
		    
			try
		 	 {  
				/*
				 * 与网页http://www.ecice06.com/cn/进行连接和提取数据
				 */
				manager = Page.getConnectionManager();
			    Parser parser = new Parser(manager.openConnection
			    ("http://www.ecice06.com/cn/search_gjdo.asp?page="+n+"&pagesize=10&sel_zazhimc=计算机工程&sel_niandu=&sel_qihao=&txt_qishiye=&txt_doi=&txt_zuozhe="+name+"&txt_zuozhe2="+name1+"&txt_zuozhedw="+name2+"&txt_wenti="+name3+"&txt_zhaiyao="+name4+"&txt_guanjianci="+name5+"&txt_fenleihao="+name6+"&sel_niandus=&sel_qihaos=&sel_niandue=&sel_qihaoe=&rad_px=zuozhexm,kanchurq%20desc"));
			    parser.setEncoding("GB2312");
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */
			    
			    NodeFilter filter = new AndFilter(new TagNameFilter("form"),
					    	new HasChildFilter(new TagNameFilter("table")));
				NodeList nodelist=parser.parse(filter);
				NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
				while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
				if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regex = Regex.regex(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
					reader =  new BufferedReader(new StringReader(regex));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				     reline =replace.replace(line); 
					
				     htm.append(reline+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
				
		 	 
		     }
			
		 	 
			catch(Exception e)
			{}
			
		  }
	   	 
	   	 
	   	 
	   	 
	   	 
	  
	    
	  /*
	   * 与http://www.computerapplications.com.cn/网页连接
	   */  
	
		 
	   	 
	   	for(i = 1;i<100;i++)
		  { n = i;
		 
		    
			try
		 	 {  
				/*
				 * 与网页进行连接和提取数据
				 */
	   		 manager = Page.getConnectionManager();
			    Parser parser = new Parser(manager.openConnection
			    ("http://www.computerapplications.com.cn/cn/search_gjdo.asp?page="+n+"&pagesize=10&sel_zazhimc=计算机应用&sel_niandu=&sel_qihao=&txt_qishiye=&txt_doi=&txt_zuozhe="+name+"&txt_zuozhe2="+name1+"&txt_zuozhedw="+name2+"&txt_wenti="+name3+"&txt_zhaiyao="+name4+"&txt_guanjianci="+name5+"&txt_fenleihao="+name6+"&sel_niandus=&sel_qihaos=&sel_niandue=&sel_qihaoe=&rad_px=zuozhexm,kanchurq%20desc"));		    
			    parser.setEncoding("GB2312");
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */
			    
	   	   NodeFilter filter = new AndFilter(new TagNameFilter("form"),
					    	new HasChildFilter(new TagNameFilter("table")));
				NodeList nodelist=parser.parse(filter);
				NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	      if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regex = Regex.regex(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regex));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				     reline =place.replace(line); 
					
				     htm.append(reline+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
				
		 	 
		   }
			
		 	 
			catch(Exception e)
			{}
			
		  }
		   
	   	
	   	
	   	
	   	
	   	/*
	   	 * 对http://ic.sia.cn/qikan/coldpaperdo.asp信息与控制网页进行连接
	   	 */
	   	
	   	
		for(i = 1;i<100;i++)
		  { n = i;
		 
		   Parser parser = null;
			try
		 	 {  
				/*
				 * 与网页进行连接和提取数据
				 */
				
				
			//	http://ic.sia.cn/qikan/coldpaperdo.asp?page=2&niandu=&qihao=&tiaojian=题目&value=网络
				/*
				 * 假设是按作者1查找论文
				 */
			   
				if( name != null && (name1 == null || name1.equals("")) && (name2 == null || name2.equals("")) && (name3 == null || name3.equals("")) && (name4 == null || name4.equals("")) && (name5 == null || name5.equals("")) && (name6==null || name6.equals("")) )
			   {
	   		    manager = Page.getConnectionManager();
			    parser = new Parser(manager.openConnection("http://ic.sia.cn/qikan/coldpaperdo.asp?page="+n+"&niandu=&qihao=&tiaojian=作者&value="+name+""));		    
			    parser.setEncoding("GB2312");
			    /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	    NodeFilter filter = new AndFilter(new TagNameFilter("table"),new HasChildFilter(new TagNameFilter("tr")));
				
	   	
	   	    NodeList nodelist=parser.parse(filter);				
			NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	  if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regexon = Regexone.regex1(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regexon));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				    // reline =place.replace(line); 
					
				     htm.append(line+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
				
		 	 
		   }
			
		 	 
			
			    
			  
			   /*
			    * 假设是按作者2查找
			    */
			   
			   
			 
				if( (name == null || name.equals("")) && name1 != null && (name2 == null || name2.equals("")) && (name3 == null || name3.equals("")) && (name4 == null || name4.equals("")) && (name5 == null || name5.equals("")) && (name6==null || name6.equals("")) )
			   {
	   		    manager = Page.getConnectionManager();
			    parser = new Parser(manager.openConnection("http://ic.sia.cn/qikan/coldpaperdo.asp?page="+n+"&niandu=&qihao=&tiaojian=作者&value="+name1+""));		    
			    parser.setEncoding("GB2312");
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	    NodeFilter filter = new AndFilter(new TagNameFilter("table"),new HasChildFilter(new TagNameFilter("tr")));
				
	   	
	   	    NodeList nodelist=parser.parse(filter);				
			NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	  if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regexon = Regexone.regex1(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regexon));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				    // reline =place.replace(line); 
					
				     htm.append(line+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
			   }
			   
			   
			   
			   
			   /*
			    * 假设是按作者单位查找
			    */
			   
			  
				if( ( name == null || name.equals("")) && (name1 == null || name1.equals("")) && name2 != null  && (name3 == null || name3.equals("")) && (name4 == null || name4.equals("")) && (name5 == null || name5.equals("")) && (name6==null || name6.equals("")) )
			   {
	   		    manager = Page.getConnectionManager();
			    parser = new Parser(manager.openConnection("http://ic.sia.cn/qikan/coldpaperdo.asp?page="+n+"&niandu=&qihao=&tiaojian=作者单位&value="+name2+""));		    
			    parser.setEncoding("GB2312");
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	    NodeFilter filter = new AndFilter(new TagNameFilter("table"),new HasChildFilter(new TagNameFilter("tr")));
				
	   	
	   	    NodeList nodelist=parser.parse(filter);				
			NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	  if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regexon = Regexone.regex1(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regexon));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				    // reline =place.replace(line); 
					
				     htm.append(line+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
			   }
			   
			   
			   /*
			    * 假设是按题目查找
			    */
			   
			  //if( name == null || name.equals("") && name1 == null || name1.equals("") && name2 == null || name2.equals("") && name3 != null && name4 == null || name4.equals("") && name5 == null || name5.equals("") && name6==null || name6.equals("") )
				if( ( name == null || name.equals("")) && (name1 == null || name1.equals("")) && name3 != null  && (name2 == null || name2.equals("")) && (name4 == null || name4.equals("")) && (name5 == null || name5.equals("")) && (name6==null || name6.equals("")) )

			   {
	   		    manager = Page.getConnectionManager();
			    parser = new Parser(manager.openConnection("http://ic.sia.cn/qikan/coldpaperdo.asp?page="+n+"&niandu=&qihao=&tiaojian=题目&value="+name3+""));		    
			    parser.setEncoding("GB2312");
			    
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	    NodeFilter filter = new AndFilter(new TagNameFilter("table"),new HasChildFilter(new TagNameFilter("tr")));
				
	   	
	   	    NodeList nodelist=parser.parse(filter);				
			NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	  if(equit.equals(but) == false)
				{
					equit = but;
					
					//System.out.print(but);
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regexon = Regexone.regex1(but);
					
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regexon));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				     //reline =place.replace(line); 
					
				     htm.append(line+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
			   }
			   
			   
			   /*
			    * 假设是按摘要查找
			    */
			   
			   
			   
			   //if(name ==null && name1 ==null && name2 == null && name3 == null && name4 != null && name5 == null && name6 == null )
				if( ( name == null || name.equals("")) && (name1 == null || name1.equals("")) && name4 != null  && (name3 == null || name3.equals("")) && (name2 == null || name2.equals("")) && (name5 == null || name5.equals("")) && (name6==null || name6.equals("")) )
			   {
	   		    manager = Page.getConnectionManager();
			    parser = new Parser(manager.openConnection("http://ic.sia.cn/qikan/coldpaperdo.asp?page="+n+"&niandu=&qihao=&tiaojian=摘要&value="+name4+""));		    
			    parser.setEncoding("GB2312");
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	    NodeFilter filter = new AndFilter(new TagNameFilter("table"),new HasChildFilter(new TagNameFilter("tr")));
				
	   	
	   	    NodeList nodelist=parser.parse(filter);				
			NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	  if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regexon = Regexone.regex1(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regexon));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				     //reline =place.replace(line); 
					
				     htm.append(line+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
			   }
			   
			   
			   /*
			    * 假设按关键词查找
			    */
			   
			   
			   
			   if(name ==null && name1 ==null && name2 == null && name3 == null && name4 == null && name5 != null && name6 == null )
			   {
	   		    manager = Page.getConnectionManager();
			    parser = new Parser(manager.openConnection("http://ic.sia.cn/qikan/coldpaperdo.asp?page="+n+"&niandu=&qihao=&tiaojian=关键词&value="+name5+""));		    
			    parser.setEncoding("GB2312");
			    
			    /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	    NodeFilter filter = new AndFilter(new TagNameFilter("table"),new HasChildFilter(new TagNameFilter("tr")));
				
	   	
	   	    NodeList nodelist=parser.parse(filter);				
			NodeIterator it=nodelist.elements();
				
				/*
				 * 过滤之后的内容
				 */
				
	   	  while(it.hasMoreNodes()){
					
					Node node =(Node)it.nextNode();
					
					 but = node.toHtml();
					 
					 
				}
				
				/*
				 *用来判断是否到了最后一页 
				 */
				
	   	  if(equit.equals(but) == false)
				{
					equit = but;
					
					/*
					 * 通过正则表达式提取有用的信息
					 */
					
					regexon = Regexone.regex1(but);
					//System.out.print(but);
					//封装字符串使用readLine()方法
				   reader =  new BufferedReader(new StringReader(regexon));
					
		     	 }
				else
				{
					break;
				}
				line = reader.readLine();
				
				/*
				 * 读所有的字符串
				 */
				StringBuffer htm = new StringBuffer(); //缓存空间
				
				/*
				 * 读所有的字符串
				 */
				
				 while(line!= null)

				{   				
					/*
					 * 调用替换方法替换页面中".."成"http://www.ecice06.com"
					 */
					
				     //reline =place.replace(line); 
					
				     htm.append(line+'\n');//添加到缓存里面
					
				     line = reader.readLine();
				}
				reline = htm.toString();
				
			   /*
			    * 存字符串至池中
			    */
				
				aticledao.save(reline);
				
				//System.out.print("g"); //测试输出
			   }
		 	 }
			    
			   /*
				    * 对网页上的信息进行初次过滤
				 */   
	   	   
			
		 	 
			catch(Exception e)
			{}
			
		  }
		
		
			list = aticledao.getList();//获取池中的内容
			n = aticledao.getN(); //获取总的页数
			String n1 = new Integer(n).toString(); //转换成字符串型
			session.setAttribute("nub",n1);//存入seesion中
			
			//System.out.print("n="+n);
			
			session.setAttribute("list",list);//存入session中
			return mapping.findForward("suc"); 	  

	   }
			
			
			
			
		 			
        
  }
