/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package index.query.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 04-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="queryForm"
 */
public class QueryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private String text ;
	/** name property */
	private String name;

	/** name1 property */
	private String name1;

	/** name2 property */
	private String name2;
	
	/** name3 property */
	private String name3;
	
	/** name3 property */
	private String name4;

	/** name3 property */
	private String name5;

	/** name3 property */
	private String name6;


	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors error = new ActionErrors();
		if( (this.name == null || "".equals(this.name)) &&
			(this.name1 == null || "".equals(this.name1)) &&
			(this.name2 == null || "".equals(this.name2)) &&
			(this.name3 == null || "".equals(this.name3)) &&
			(this.name4 == null || "".equals(this.name4)) &&
			(this.name5 == null || "".equals(this.name5))&&
			(this.name6 == null || "".equals(this.name6)))
		{
			error.add(this.name2, new ActionMessage("name2.null"));
		}
		
		return error;
	}
	

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the name3.
	 * @return String
	 */
	public String getName3() {
		return name3;
	}

	/** 
	 * Set the name3.
	 * @param name3 The name3 to set
	 */
	public void setName3(String name3) {
		this.name3 = name3;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the name1.
	 * @return String
	 */
	public String getName1() {
		return name1;
	}

	/** 
	 * Set the name1.
	 * @param name1 The name1 to set
	 */
	public void setName1(String name1) {
		this.name1 = name1;
	}

	/** 
	 * Returns the name2.
	 * @return String
	 */
	public String getName2() {
		return name2;
	}

	/** 
	 * Set the name2.
	 * @param name2 The name2 to set
	 */
	public void setName2(String name2) {
		this.name2 = name2;
	}


	public String getName4() {
		return name4;
	}


	public void setName4(String name4) {
		this.name4 = name4;
	}


	public String getName5() {
		return name5;
	}


	public void setName5(String name5) {
		this.name5 = name5;
	}


	public String getName6() {
		return name6;
	}


	public void setName6(String name6) {
		this.name6 = name6;
	}


	public String getText() {
		return text;
	}


	public void setText(String text) {
		this.text = text;
	}
}