/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package index.query.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2008
 * 
 * XDoclet definition:
 * @struts.form name="simpleForm"
 */
public class SimpleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** text1 property */
	private String text1;
	private int pa;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors error = new ActionErrors();
		if(this.text1 == null || "".equals(text1))
		{
			error.add(this.text1,new ActionMessage("text.null"));
		}
		return error;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the text1.
	 * @return String
	 */
	public String getText1() {
		return text1;
	}

	/** 
	 * Set the text1.
	 * @param text1 The text1 to set
	 */
	public void setText1(String text1) {
		this.text1 = text1;
	}

	public int getPa() {
		return pa;
	}

	public void setPa(int pa) {
		this.pa = pa;
	}
}